stages:
  - install_dependencies
  - run_dev
  - test

install_dependencies:
  stage: install_dependencies
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Dependencies installed"

run_dev:
  stage: run_dev
  script:
    - echo "Running development server..."
    - npm run dev

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests passed successfully!"
