stages:
  - install_dependencies
  - test

install_dependencies:
  stage: install_dependencies
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Dependencies installed"
  artifacts:
    paths:
      - node_modules/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests passed successfully!"
