image: node:latest

stages:
  - build

variables:
  NODE_MODULES_CACHE_PATH: node_modules/

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${NODE_MODULES_CACHE_PATH}

before_script:
  - echo "Installing dependencies"
  - npm install

build:
  stage: build
  script:
    - echo "Building the app from branch $CI_COMMIT_BRANCH"
    - npm run dev
