stages:
  - build
  - run
  - test

variables:
  NODE_MODULES_CACHE_PATH: node_modules/

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - ${NODE_MODULES_CACHE_PATH}

install_dependencies:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Dependencies installed"

run:
  stage: run
  script:
    - echo "Running the app"
    - npm run dev
    - echo "App is running"

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests passed successfully!"
